# -*- coding: utf-8 -*-
"""ML_tungsten_young's_modulus.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1coIaBFGKZxV0Hvn2uR6tIoJU8PHz6a_d
"""

import pandas as pd

df = pd.read_csv("Final_Dataset.csv")
print(df.head())
print(df.describe())
print(df.drop(columns=['Direction']).corr())

import seaborn as sns
import matplotlib.pyplot as plt

sns.pairplot(df)
plt.show()

sns.heatmap(df.drop(columns=['Direction']).corr(), annot=True, cmap="coolwarm")
plt.show()

from sklearn.model_selection import train_test_split

X = df[["Temperature", "StrainRate", "Direction", "BoxSize"]]
y = df["YoungsModulus_GPa"]

# Encode direction
X = pd.get_dummies(X, columns=["Direction"])

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_absolute_error

model = RandomForestRegressor(n_estimators=300, random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("R2 Score:", r2_score(y_test, y_pred))
print("MAE:", mean_absolute_error(y_test, y_pred))

import matplotlib.pyplot as plt

importance = model.feature_importances_
for col, val in zip(X.columns, importance):
    print(col, "=", val)

plt.bar(X.columns, importance)
plt.title("Feature Importance")
plt.show()

import pickle

with open("YoungModulus_Predictor.pkl", "wb") as f:
    pickle.dump(model, f)

sample = [[300, 0.001, 10, 0, 1, 0]] # one-hot direction (x,y,z)
print(model.predict(sample))

import numpy as np
# ---------- ACTUAL vs PREDICTED (Scatter Parity Plot) ----------
plt.figure(figsize=(7,6))
plt.scatter(y_test, y_pred, edgecolors='black', linewidth=1.2)
plt.plot([min(y_test), max(y_test)], [min(y_test), max(y_test)], 'r--', linewidth=2)  # perfect fit line
plt.xlabel("Actual Young's Modulus (GPa)", fontsize=12, fontweight='bold')
plt.ylabel("Predicted Young's Modulus (GPa)", fontsize=12, fontweight='bold')
plt.title("Predicted vs Actual Young's Modulus", fontsize=14, fontweight='bold')
plt.grid(True)
plt.tight_layout()
plt.show()

# ---------- OPTIONAL: COMPARATIVE LINE PLOT ----------
plt.figure(figsize=(8,5))
plt.plot(np.arange(len(y_test)), y_test.values, marker='o', label="Actual", linewidth=2)
plt.plot(np.arange(len(y_pred)), y_pred, marker='s', label="Predicted", linewidth=2)
plt.xlabel("Sample Index", fontsize=12, fontweight='bold')
plt.ylabel("Young's Modulus (GPa)", fontsize=12, fontweight='bold')
plt.title("Actual vs Predicted Young's Modulus (Sample-wise)", fontsize=14, fontweight='bold')
plt.legend(fontsize=10)
plt.grid(True)
plt.tight_layout()
plt.show()

