# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jlN4t7vChhR2LUUd3vYmg35GwGUqt8HM
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import linregress

# ---------------- USER INPUT ---------------- #
files = [
    "stress_strain_300_0.001_x_10.dat",
    "stress_strain_300_0.001_y_10.dat",
    "stress_strain_300_0.001_z_10.dat"
]
zoom_range = 0.04        # max strain for zoom region
elastic_limit = 0.02     # strain limit for linear fitting (Young's Modulus)
# --------------------------------------------- #

# ---------- STYLING SETTINGS ----------
bold_font = {'weight': 'bold', 'size': 16}
legend_properties = {'weight': 'bold', 'size': 10}

results = []  # Store modulus for each file

# ---------- MAIN FULL PLOT ----------
fig, ax = plt.subplots(figsize=(9, 7))

for file in files:
    data = np.loadtxt(file)
    strain = data[:, 0]
    stress = data[:, 1] * 0.0001  # bar → GPa

    # Linear regression for Young's Modulus
    mask = strain <= elastic_limit
    strain_lin = strain[mask]
    stress_lin = stress[mask]

    slope, intercept, r_value, p_value, std_err = linregress(strain_lin, stress_lin)
    E = slope
    R2 = r_value**2

    # Store results for later annotation
    results.append((file, E, R2))

    label = f"{file.replace('stress_strain_', '').replace('.dat', '')} | E={E:.2f} GPa"
    ax.plot(strain, stress, linewidth=2, linestyle='-', label=label)

# Labels & Title
ax.set_xlabel("Strain", fontsize=16, fontweight='bold', labelpad=8)
ax.set_ylabel("Stress (GPa)", fontsize=16, fontweight='bold', labelpad=8)
ax.set_title("Combined Stress–Strain Curve with Young's Modulus", fontdict=bold_font)

# Styling
for axis in ['top', 'bottom', 'left', 'right']:
    ax.spines[axis].set_linewidth(1.8)
plt.xticks(weight='bold', fontsize=12)
plt.yticks(weight='bold', fontsize=12)
plt.tick_params(direction='in', length=5, width=1.4)

ax.legend(prop=legend_properties, loc='upper left', frameon=True, edgecolor='black', ncol=1)

# Annotation text box
text = "\n".join([f"{f.replace('stress_strain_', '').replace('.dat', '')}: E={E:.2f} GPa, R²={R2:.4f}"
                  for f, E, R2 in results])

plt.text(0.65, 0.35, text, transform=ax.transAxes, fontsize=10,
         bbox=dict(facecolor='white', edgecolor='black'))

plt.tight_layout()
plt.savefig("Stress_Strain_Combined_With_E.png", dpi=300, bbox_inches='tight')
plt.savefig("Stress_Strain_Combined_With_E.pdf", bbox_inches='tight')
plt.show()

