# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yXc-xBSjoDx6ViKLTQHJkq29ZC8BuZt3
"""

import os
import itertools

# --------- LAMMPS executable ----------
LAMMPS_CMD = "lmp"   # change if needed: lmp_serial / lmp_mpi / mpirun -np 4 lmp_mpi

# --------- Parameter sets ----------
temps       = [100, 300, 600]
strainrates = [1e-4, 1e-3, 1e-2]
dirs        = ["x", "y", "z"]
boxsizes    = [8, 10, 12]

# --------- Simulation loop ----------
count = 0
for T, SR, DIR, L in itertools.product(temps, strainrates, dirs, boxsizes):

    count += 1
    print(f"\n Running simulation #{count} --> T={T}, SR={SR}, DIR={DIR}, BOX={L}")

    # Build execution command
    cmd = f'{LAMMPS_CMD} -in input_lammps.txt -var temp {T} -var strain_rate {SR} -var dir {DIR} -var boxsize {L}'

    # Execute
    os.system(cmd)

print(f"\n Done! Total simulations executed: {count}")